name = "oring_schedule"
compatibility_date = "2023-08-14"

# routes = [
# 	{ pattern = "oringapp.workers.dev/*", zone_name = "workers.dev" }
# ]

services = [
  { binding = "CALL_API", service = "oring_server_check_bot" },
]

[triggers]
crons = ["*/10 * * * *"]